# Generated by Django 6.1 on 2026-08-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.URLField()),
                ('Category', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Restaurant_Name', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
