# Generated by Django 6.0.3 on 2026-08-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='OldPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='Tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='TagType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
