# Generated by Django 6.0.3 on 2026-08-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_oldprice_item_rating_item_tag_item_tagtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.URLField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
