# Generated by Django 6.0.3 on 2026-08-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_foodshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.URLField()),
                ('Role', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=50)),
                ('Instagram', models.URLField(blank=True, null=True)),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('Twitter', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
