# Generated by Django 6.0.3 on 2026-08-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.URLField()),
                ('Role', models.CharField(max_length=100)),
                ('Rating', models.IntegerField(default=5)),
                ('Description', models.TextField()),
            ],
        ),
    ]
