# Generated by Django 6.1 on 2026-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Guests', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=20)),
                ('SpecialRequests', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('TableNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
